#[[gettingstarted]]
#  name = "Documentation"
#  weight = 4
#  identifier = "documentation"
#  url = "/docs/"

#[[configure]]
#  name = "Configuring Owncast"
#  weight = 10
#  identifier = "config"
#  url = "/docs/configuration/"

#[[integrations]]
#  name = "APIs and Integrations"
#  weight = 200
#  identifier = "integrations"
#  url = "/docs/integrations/"

[[main]]
  name = "หน้าหลัก"
  url = "https://ufapro888s.co/"
  weight = 10

#[[main]]
#  name = "Docs"
#  url = "/docs/"
#  weight = 20


#[[main]]
#  name = "Releases"
#  url = "/releases"
#  weight = 30


#[[social]]
#  name = "หน้าหลัก"
# pre = "<img src='https://ufapro888s.co/wp-content/uploads/2021/07/cropped-LOGO.png' alt='logo-ufapro888s' width='100%' >"
#  url = "https://ufapro888s.co/"
#  post = "v0.1.0"
#  weight = 20

[[social]]
  name = "ไฮไลท์ ฟุตบอล"
  pre = "<img src='https://www.img.in.th/images/f9bbdfebc27f6e3d8e727a87a7458f1a.png' alt='logo-ufapro888s' width='100%' >"
  url = "https://ufatop1.net/"
  weight = 30

#[[quickstart]]
#  name = "Quickstart"
#  weight = 10
#  identifier = "quickstart"
#  url = "/quickstart/"

# [[footer]]
#   name = "Contact"
#   url = "/contact"
#   weight = 10

# [[footer]]
#   name = "Contribute"
#   url = "/contribute"
#   weight = 10

# [[footer]]
#   name = "FAQ"
#   url = "/faq"
#   weight = 10