[build]
  publish = "public"
  functions = "functions"

[build.environment]
  HUGO_VERSION = "0.88.1"
  NODE_VERSION = "14.17.0"
  NPM_VERSION = "7.18.1"

[context.production]
  command = "hugo -b $URL --gc --minify && npm run build:functions"

[context.deploy-preview]
  command = "hugo -b $DEPLOY_PRIME_URL --gc --minify"

[context.branch-deploy]
  command = "hugo -b $DEPLOY_PRIME_URL --gc --minify"
